### ISSUE TITLE
Code clean up and updateing for use

### ISSUE THREAD

**Issue by cegme** [akash-2303/livechat#1]
Flexible deployment:
You should update your code to be deployable from almost anywhere.

1. Listen to 0.0.0.0 and add the port number as a parameter

2. Add the chat message file as a parameter

3. Do not encode the data as ASCII. Encode with utf-8

4. Save the full output to a sqlite file or a data file. Then you can print in whatever format you want.

**Comment by akash-2303** [comment]
Forgot to tag but all features are implemented and merged in main.
